USE [master]
GO

/****** Object:  Database [EnglishMentor]    Script Date: 12/14/2018 4:02:34 PM ******/
CREATE DATABASE [EnglishMentor]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EnglishMentor', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\EnglishMentor.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EnglishMentor_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\EnglishMentor_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EnglishMentor] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EnglishMentor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EnglishMentor] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EnglishMentor] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EnglishMentor] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EnglishMentor] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EnglishMentor] SET ARITHABORT OFF 
GO

ALTER DATABASE [EnglishMentor] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EnglishMentor] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EnglishMentor] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EnglishMentor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EnglishMentor] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EnglishMentor] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EnglishMentor] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EnglishMentor] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EnglishMentor] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EnglishMentor] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EnglishMentor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EnglishMentor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EnglishMentor] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EnglishMentor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EnglishMentor] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EnglishMentor] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EnglishMentor] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EnglishMentor] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EnglishMentor] SET  MULTI_USER 
GO

ALTER DATABASE [EnglishMentor] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EnglishMentor] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EnglishMentor] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EnglishMentor] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EnglishMentor] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EnglishMentor] SET  READ_WRITE 
GO


