//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoPerfile
    {
        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public string Perioricidad { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string UsuarioActualiza { get; set; }
        public decimal Status { get; set; }
    }
}
