//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public string Nombre2 { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public decimal Telefono1 { get; set; }
        public Nullable<decimal> Telefono2 { get; set; }
        public decimal CodigoPostal { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string DelegacionMunicipio { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public decimal TipoPerfil { get; set; }
        public string CodigoPromo { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<decimal> ConteoReferenciados { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string UsuarioActualiza { get; set; }
        public decimal Status { get; set; }
    }
}
