//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnglishMentorEntities : DbContext
    {
        public EnglishMentorEntities()
            : base("name=EnglishMentorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatalogoPerfile> CatalogoPerfiles { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<PrecioPerfile> PrecioPerfiles { get; set; }
    }
}
