//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioPerfile
    {
        public decimal IdPerfil { get; set; }
        public string Perioricidad { get; set; }
        public decimal PrecioNormal { get; set; }
        public decimal Iva { get; set; }
        public decimal PrecioFinal { get; set; }
        public Nullable<decimal> DescuentoMaximoReferenciaPCT { get; set; }
        public Nullable<decimal> DescuentoMaximoReferencia { get; set; }
        public Nullable<decimal> DescuentoReferencia1PCT { get; set; }
        public Nullable<decimal> DescuentoReferencia2PCT { get; set; }
        public Nullable<decimal> DescuentoReferencia3PCT { get; set; }
        public Nullable<decimal> DescuentoReferencia4PCT { get; set; }
        public Nullable<decimal> DescuentoReferencia1 { get; set; }
        public Nullable<decimal> DescuentoReferencia2 { get; set; }
        public Nullable<decimal> DescuentoReferencia3 { get; set; }
        public Nullable<decimal> DescuentoReferencia4 { get; set; }
        public Nullable<decimal> ComisionSistemasPCT { get; set; }
        public Nullable<decimal> ComisionSistemas { get; set; }
        public Nullable<decimal> ImpuestoSistemas { get; set; }
        public Nullable<decimal> ComisionDespImpuestoSistemas { get; set; }
        public Nullable<decimal> ComisionInstructorPCT { get; set; }
        public Nullable<decimal> ComisionInstructor { get; set; }
        public Nullable<decimal> ImpuestoInstructor { get; set; }
        public Nullable<decimal> ComisionDespImpuestoInstructor { get; set; }
        public Nullable<decimal> ComisionVendedorPCT { get; set; }
        public Nullable<decimal> ComisionVendedor { get; set; }
        public Nullable<decimal> ImpuestoVendedor { get; set; }
        public Nullable<decimal> ComisionDespImpuestoVendedor { get; set; }
        public Nullable<decimal> GananciaNeta { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string UsuarioActualiza { get; set; }
        public decimal Status { get; set; }
    }
}
